apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: atlas
spec:
  version: {{ .TagName }}
  homepage: https://github.com/s-urbaniak/kube-atlas-cli
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/s-urbaniak/kube-atlas-cli/releases/download/{{ .TagName }}/atlas_darwin_amd64.tar.gz" .TagName }}
    files:
      - from: "./atlas"
        to: "."
      - from: LICENSE
        to: "."
    bin: "atlas"
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    {{addURIAndSha "https://github.com/s-urbaniak/kube-atlas-cli/releases/download/{{ .TagName }}/atlas_darwin_arm64.tar.gz" .TagName }}
    files:
      - from: "./atlas"
        to: "."
      - from: LICENSE
        to: "."
    bin: "atlas"
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/s-urbaniak/kube-atlas-cli/releases/download/{{ .TagName }}/atlas_linux_amd64.tar.gz" .TagName }}
    files:
      - from: "./atlas"
        to: "."
      - from: LICENSE
        to: "."
    bin: "atlas"
  - selector:
      matchLabels:
        os: linux
        arch: arm
    {{addURIAndSha "https://github.com/s-urbaniak/kube-atlas-cli/releases/download/{{ .TagName }}/atlas_linux_arm.tar.gz" .TagName }}
    files:
      - from: "./atlas"
        to: "."
      - from: LICENSE
        to: "."
    bin: "atlas"
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    {{addURIAndSha "https://github.com/s-urbaniak/kube-atlas-cli/releases/download/{{ .TagName }}/atlas_linux_arm64.tar.gz" .TagName }}
    files:
      - from: "./atlas"
        to: "."
      - from: LICENSE
        to: "."
    bin: "atlas"
  - selector:
      matchLabels:
        os: windows
        arch: arm64
    {{addURIAndSha "https://github.com/s-urbaniak/kube-atlas-cli/releases/download/{{ .TagName }}/atlas_windows_arm64.zip" .TagName }}
    files:
      - from: "/atlas.exe"
        to: "."
      - from: LICENSE
        to: "."
    bin: "atlas.exe"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/s-urbaniak/kube-atlas-cli/releases/download/{{ .TagName }}/atlas_windows_amd64.zip" .TagName }}
    files:
      - from: "/atlas.exe"
        to: "."
      - from: LICENSE
        to: "."
    bin: "atlas.exe"
  - selector:
      matchLabels:
        os: windows
        arch: arm
    {{addURIAndSha "https://github.com/s-urbaniak/kube-atlas-cli/releases/download/{{ .TagName }}/atlas_windows_arm.zip" .TagName }}
    files:
      - from: "/atlas.exe"
        to: "."
      - from: LICENSE
        to: "."
    bin: "atlas.exe"
  shortDescription: A kubectl plugin to interact with MongoDB Atlas leveraging the MongoDB Atlas Operator.
